### ISSUE TITLE
TODO: rename repository to df-translation-toolkit

### ISSUE THREAD

**Issue by insolor** [dfint/df-translation-toolkit#54]
- [x] rename repository
- [x] publish release with new name
- [x] add repo to pypi index
- [x] change name and version in automation repository
